# Generated by Django 5.0 on 2023-12-12 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fields_Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.TextField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_field',
        ),
        migrations.AddField(
            model_name='project',
            name='project_field',
            field=models.ManyToManyField(to='mainApp.fields_project'),
        ),
    ]
