# Generated by Django 4.2.6 on 2024-01-16 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_messages_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='pid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainApp.project'),
        ),
    ]
