# Generated by Django 5.0 on 2024-01-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_messages_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_amount',
            field=models.IntegerField(default=0),
        ),
    ]
