# Generated by Django 5.0 on 2024-01-22 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0005_project_project_amount'),
        ('mainApp', '0005_resume_pid'),
    ]

    operations = [
    ]
